### ISSUE TITLE
[Bug] Some tag pages have duplicate content.

### ISSUE THREAD

**Issue by m-chrzan** [LukeSmithxyz/based.cooking#552] opened 2021-04-05 14:54 UTC
On some tag pages (haven't found a pattern for what this could be correlated with) have the recipe list and site footer duplicated. E.g. [spread](https://based.cooking/@spread), [turkey](https://based.cooking/@turkey), [tuna](https://based.cooking/@tuna).

![2021-04-05-165240_864x571_scrot](https://user-images.githubusercontent.com/16142976/113587760-8ab9e500-962f-11eb-864f-05ce7702ba05.png)

**Comment by hallzy** [comment] 2021-04-05 18:03
@LukeSmithxyz 

It is non deterministic. I was able to reproduce this by running `make build` twice at the same time.

What might be happening is that when something is merged in, the make file does it's build, but before it can finish something, another change is merged in triggering 2 builds at the same time.

In my test I also ended up with a bunch of recipes that had the footer multiple times as well, so you might be able to find those as well.

Not sure what the best way forward to avoid this is. Waiting for the upload workflow to finish before merging something else would probably work.

Otherwise we'd need a way to make the makefile wait for other builds to finish.

**Comment by m-chrzan** [comment] 2021-04-05 19:13
Ah, that could do it. The easiest fix would be to just `make clean` in the deployment script. That somewhat defeats the incremental nature of the generator but would definitely be deterministic.

Does GitHub Actions kill a previously merged PR's workflow if it was ongoing and a new PR is merged? If all workflows are allowed to run to their end, some simple(ish) bash locking mechanism could be a possible solution (e.g. with `flock` like [here](https://stackoverflow.com/a/50419392)).

**Comment by hallzy** [comment] 2021-04-05 19:27
> The easiest fix would be to just make clean in the deployment script.

This doesn't work either. If you run `make clean build`, it will clean and then start building like normal. A new merge happens and that one calls `make clean build` as well, which eliminates the work that the first build has done already, but the first build still continues doing what it is doing while the second one keeps going as well.

I just tried it and it actually messes up more stuff... The index page is missing the recipes altogether in my test and has them below the footer instead (and has a second footer as well).

> Does GitHub Actions kill a previously merged PR's workflow if it was ongoing and a new PR is merged?

No, it doesn't. Some kind of locking thing might work as you mention. Or do the deployment once per day, or maybe twice or something... this way you would never have 2 builds running simultaneously, but it also means you would need to wait for changes to take effect.

**Comment by m-chrzan** [comment] 2021-04-05 19:37
> > The easiest fix would be to just make clean in the deployment script.
> 
> This doesn't work either. 

Right. I was under the assumption builds were killed upon a new PR which would have worked then.

> > Does GitHub Actions kill a previously merged PR's workflow if it was ongoing and a new PR is merged?
> 
> No, it doesn't. 

In that case locking seems like the way to go if we want to keep deployments in Actions. Otherwise, periodic deployments like you suggest. Which would probably amount to Luke installing a cron job doing `git pull && make deploy` at whatever interval makes sense.

**Comment by hallzy** [comment] 2021-04-05 19:44
I was actually still thinking action, but ya... cronjob would work to... I am pretty sure github actions have a way to do time based execution.

I just realized that the current github action is actually running the series of commands directly on Luke's webserver and the `make deploy` looks like it is just copying the files to /var/www.

So another option could be to do the build on the github server and rsync it over... because I believe every action spawns its own environment, so doing a build on a github server and copying it over would run the make stuff once per environment, and then the files are copied to Luke's server afterwards...

A race condition with the rsync causing any problems seems unlikely to me.

Lots of options I guess. The time based update would probably be the easiest, but the lock would probably be good too if we want the site to update immediately.

**Comment by samuel-hunter** [comment] 2021-04-08 05:02
It's not limited to tag pages. I'm experiencing something very similar to recipe pages themselves on the production site:
![image](https://user-images.githubusercontent.com/41240025/113970722-3445d580-97ec-11eb-921d-d1fba1c2c342.png)

[This page in particular](https://based.cooking/aglio-e-olio) [(archive.is mirror since the bug is nondeterministic)](https://archive.is/mvIcl) has the recipe content duplicated, then each individual metadata paragraph duplicated (Recipe tags, recipe posted), and then the footer duplicated.

**Closed** 2021-05-13 13:27 UTC
