### ISSUE TITLE
certain tag pages have double div class banners and footers (i.e. wine, texmex, to name a few) 

### ISSUE THREAD

**Issue by 31ias** [LukeSmithxyz/based.cooking#633] opened 2021-05-21 12:14 UTC
```
<!DOCTYPE html>
<html lang=en>
    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <link rel="icon" href="data:image/svg+xml,<svg xmlns=%22http://www.w3.org/2000/svg%22 viewBox=%220 0 100 100%22><text y=%221em%22 font-size=%2280%22>🍲</text></svg>">
        <link rel="stylesheet" href="./style.css">
        <title>Articles tagged wine -- Based Cooking</title>
        <meta name="description" content="Only Based cooking. No ads, no tracking, nothing but based cooking.">
    </head>
    <body>
<div class="banner">
    <h1>🍲 Based Cooking 🍳</h1>
    <hr/>
</div>
<p><i>Filtering recipes tagged:</i> <b>wine</b></p>
<div class="banner">
    <h1>🍲 Based Cooking 🍳</h1>
    <hr/>
</div>
<p><i>Filtering recipes tagged:</i> <b>wine</b></p>
<h2>Recipes</h2>
<ul id=artlist>
<h2>Recipes</h2>
<ul id=artlist>
<li><a href="chicken-in-red-wine-vinegar-sauce.html">Chicken in Red Wine Vinegar Sauce</a></li>
<li><a href="chicken-in-red-wine-vinegar-sauce.html">Chicken in Red Wine Vinegar Sauce</a></li>
<li><a href="italian-mulled-wine.html">Italian Mulled Wine</a></li>
<li><a href="italian-mulled-wine.html">Italian Mulled Wine</a></li>
<li><a href="mushroom-risotto.html">Mushroom risotto</a></li>
<li><a href="mushroom-risotto.html">Mushroom risotto</a></li>
</ul>
</ul>
<footer>
    <hr/>
    <a href=".">homepage</a>
    <a href="./rss.xml">RSS</a>
    <a href="./atom.xml">atom</a>
    <br>
    <p>All site content is in the Public Domain.</p>
    <p><small>Powered by <a href="https://pedantic.software/git/blogit">blogit</a></small></p>
</footer>
</body></html>
<footer>
    <hr/>
    <a href=".">homepage</a>
    <a href="./rss.xml">RSS</a>
    <a href="./atom.xml">atom</a>
    <br>
    <p>All site content is in the Public Domain.</p>
    <p><small>Powered by <a href="https://pedantic.software/git/blogit">blogit</a></small></p>
</footer>
</body></html>
```

<img width="960" alt="tags" src="https://user-images.githubusercontent.com/79116109/119134822-7c166a00-b9f2-11eb-8fcc-fb924c2423de.png">
<img width="876" alt="tags2" src="https://user-images.githubusercontent.com/79116109/119135032-bed84200-b9f2-11eb-888e-c87bb2fde207.png">

**Comment by hallzy** [comment] 2021-06-07 21:28
I think this is probably a duplicate of #552. That issue is closed now, so I don't know if it was fixed or ignored...

**Comment by ejh-github** [comment] 2021-06-08 10:53
> I think this is probably a duplicate of #552. That issue is closed now, so I don't know if it was fixed or ignored...

Do you feel blame? Are you mad? Do you feel like wolf kabob Roth vantage? Gefrannis booj pooch boo jujube; bear-ramage. Jigiji geeji geeja geeble Google. Begep flagaggle vaggle veditch-waggle bagga?

**Comment by DGKSK8LIFE** [comment] 2021-06-08 20:02
You speak my language sir.

**Comment by peepopoggers** [comment] 2021-06-30 21:36
ah, i see, a cultured keyboard masher

**Closed** 2021-09-15 22:21 UTC
