### ISSUE TITLE
Make tags case insensitive

### ISSUE THREAD

**Issue by tpaduraru** [LukeSmithxyz/based.cooking#411] opened 2021-03-22 16:00 UTC
[French](https://based.cooking/@French)  and [french](https://based.cooking/@french)  are 2 different tags with different recipes.

**Comment by HappyClem** [comment] 2021-03-22 16:04
Duplicate of #406

**Comment by tpaduraru** [comment] 2021-03-22 16:12
duplicate issue

**Closed** 2021-03-22 16:12 UTC

**Comment by hallzy** [comment] 2021-03-22 16:15
This is fixed in the repo, it just hasn't reflected in the website yet

**Comment by HappyClem** [comment] 2021-03-23 09:21
I'm late here, but how does the tag system works ? Is it created server side or can is it just html href I don't know about ?

**Comment by hallzy** [comment] 2021-03-23 15:56
Recipes contain a list of tags at the bottom of their markdown file like `;tags: tag1 tag2 tag3`. Whenever a commit is pushed or merged into master it executes the makefile which builds all the HTML files from markdown, including the tags. So the tagging system is all built from the makefile.

The reason the change hadn't reflected on the site yet was because CI was broken for a bit there #413
