### ISSUE TITLE
Can't pass all checks

### ISSUE THREAD

**Issue by VladPetryshyn** [LukeSmithxyz/based.cooking#551] opened 2021-04-04 16:04 UTC
## Hello, I have added vareniki, but I can't pass all the checks #550

**Comment by hallzy** [comment] 2021-04-04 17:25
I've reviewed your PR and mentioned the cause. Note that the reason for failure is more obvious with the new script that hasn't been merged yet #462

Please remember to close this issue.

**Comment by VladPetryshyn** [comment] 2021-04-05 09:08
Thanks

**Closed** 2021-04-05 09:09 UTC
