### ISSUE TITLE
BASED ON WHAT???

### ISSUE THREAD

**Issue by jirrob** [LukeSmithxyz/based.cooking#427] opened 2021-03-23 07:46 UTC
I do not understand. What is the cooking based on???? What is it???? 
ANSWER ME!!! NOW!!! **infuriated emoji**

**Comment by m-chrzan** [comment] 2021-03-23 09:47
Dupe of #64

**Comment by LukeSmithxyz** [comment] 2021-03-23 18:32
See #64

**Closed by LukeSmithxyz** 2021-03-23 18:32 UTC
